services:
  espn-plus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config:/app/config
    environment:
      - NODE_ENV=development
    command: npm start
    restart: always
    depends_on:
      - php-proxy
  php-proxy:
    image: leduong/php:proxy
    environment:
      - PROXY_URL=
    restart: always
