curl -X POST http://localhost:8283 \
     -H "Content-Type: application/json" \
     -d '{
          "url": "https://ipinfo.io/json",
          "header": {
            "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36"
          },
          "body": {}
        }'
